=== PauMasia/paginesEstatiquesAll/src/main/json/schemaCantantes.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "name",
      "birth",
      "country",
      "artistName",
      "actualImage"
    ],
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "birth": {
        "type": "number"
      },
      "country": {
        "type": "string",
        "minLength": 1
      },
      "artistName": {
        "type": "string",
        "minLength": 1
      },
      "actualImage": {
        "type": "string",
        "minLength": 1
      }
    }
  }
}

=== PauMasia/paginesEstatiquesAll/src/main/json/cantantes.json
[
  {
    "name": "Aubrey Drake Graham",
    "birth": 1986,
    "country": "Canada",
    "artistName": "Drake",
    "actualImage": "../img/drake-perf.jpg"
  },
  {
    "name": "Jermaine Lamarr Cole",
    "birth": 1985,
    "country": "Germany",
    "artistName": "J. Cole",
    "actualImage": "../img/jcole-perf.jpg"
  },
  {
    "name": "Kendrick Lamar Duckworth",
    "birth": 1987,
    "country": "USA",
    "artistName": "Kendrick Lamar",
    "actualImage": "../img/kendrick-perf.jpg"
  }
]
